# Generated by Django 6.0.2 on 2026-02-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratehistoryinternalvehicle',
            name='calculated_cost_per_kl',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ratehistoryvendor',
            name='calculated_cost_per_kl',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ratehistoryvendor',
            name='water_type',
            field=models.CharField(choices=[('Drinking Water', 'Drinking Water'), ('Normal Water (Salt)', 'Normal Water (Salt)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='waterentry',
            name='water_type',
            field=models.CharField(blank=True, choices=[('Drinking Water', 'Drinking Water'), ('Normal Water (Salt)', 'Normal Water (Salt)')], max_length=50, null=True),
        ),
    ]
