# Generated by Django 6.0.2 on 2026-02-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0002_alter_ratehistoryinternalvehicle_calculated_cost_per_kl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterentry',
            name='shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waterentry',
            name='water_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
