# Generated by Django 6.0.2 on 2026-02-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0003_alter_waterentry_shift_alter_waterentry_water_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratehistoryinternalvehicle',
            name='loading_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_vehicle_rates', to='water_tracker.masterlocation'),
        ),
    ]
