# Generated by Django 6.0.2 on 2026-02-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0004_ratehistoryinternalvehicle_loading_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
