# Generated by Django 6.0.2 on 2026-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0005_masterlocation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterentry',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
