# Generated by Django 6.0.2 on 2026-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0007_yieldlocation_yieldentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldentry',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
