# Generated by Django 6.0.2 on 2026-02-18 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0008_yieldentry_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True)),
                ('consumption_type', models.CharField(choices=[('Normal', 'Normal Water Consumption'), ('Drinking', 'Drinking Water Consumption')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'consumption_locations',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_reading', models.IntegerField()),
                ('previous_reading', models.IntegerField(blank=True, null=True)),
                ('consumption_liters', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_entries', to='water_tracker.consumptionlocation')),
            ],
            options={
                'db_table': 'consumption_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
