# Generated by Django 6.0.2 on 2026-02-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0009_consumptionlocation_consumptionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'consumption_categories',
            },
        ),
        migrations.AddField(
            model_name='consumptionlocation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='water_tracker.consumptioncategory'),
        ),
    ]
