# Generated by Django 6.0.2 on 2026-02-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0010_consumptioncategory_consumptionlocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldlocation',
            name='is_manual_yield',
            field=models.BooleanField(default=False),
        ),
    ]
