# Generated by Django 6.0.2 on 2026-02-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0011_yieldlocation_is_manual_yield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionlocation',
            name='location_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='consumptionlocation',
            unique_together={('location_name', 'consumption_type')},
        ),
    ]
