# Generated by Django 6.0.2 on 2026-02-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0012_alter_consumptionlocation_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionlocation',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yieldlocation',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
