# Generated by Django 6.0.2 on 2026-02-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0013_consumptionlocation_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncategory',
            name='student_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
