# Generated by Django 6.0.2 on 2026-02-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0014_consumptioncategory_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncategory',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumptioncategory',
            name='second_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
