# Generated by Django 6.0.2 on 2026-02-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0015_consumptioncategory_is_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncategory',
            name='exclude_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
