# Generated by Django 6.0.2 on 2026-02-20 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0016_consumptioncategory_exclude_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralWaterRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('normal_water_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('drinking_water_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'general_water_rates',
                'ordering': ['-effective_date', '-date'],
            },
        ),
    ]
