# Generated by Django 6.0.2 on 2026-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0017_generalwaterrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncategory',
            name='has_student_count',
            field=models.BooleanField(default=True),
        ),
    ]
